# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}


start_step init_design
set ACTIVE_STEP init_design
set rc [catch {
  create_msg_db init_design.pb
  set_param chipscope.maxJobs 2
  create_project -in_memory -part xc7a100tcsg324-1
  set_property design_mode GateLvl [current_fileset]
  set_param project.singleFileAddWarning.threshold 0
  set_property webtalk.parent_dir D:/VivadoProject/FLXG/FLXG.cache/wt [current_project]
  set_property parent.project_path D:/VivadoProject/FLXG/FLXG.xpr [current_project]
  set_property ip_output_repo D:/VivadoProject/FLXG/FLXG.cache/ip [current_project]
  set_property ip_cache_permissions {read write} [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files -quiet D:/VivadoProject/FLXG/FLXG.runs/synth_1/FLXG.dcp
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_num_none/blk_mem_gen_num_none.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_cwk/img_cwk.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_2048/blk_mem_gen_2048.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_256/blk_mem_gen_256.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_64/blk_mem_gen_64.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_rst/img_rst.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_32/blk_mem_gen_32.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_128/blk_mem_gen_128.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_512/blk_mem_gen_512.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_fail/img_fail.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_success/img_success.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_1024/blk_mem_gen_1024.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_16/blk_mem_gen_16.xci
  read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
  read_xdc D:/VivadoProject/FLXG/FLXG.srcs/constrs_1/imports/VivadoProject/Nexys-4-DDR-Master.xdc
  link_design -top FLXG -part xc7a100tcsg324-1
  close_msg_db -file init_design.pb
} RESULT]
if {$rc} {
  step_failed init_design
  return -code error $RESULT
} else {
  end_step init_design
  unset ACTIVE_STEP 
}

start_step opt_design
set ACTIVE_STEP opt_design
set rc [catch {
  create_msg_db opt_design.pb
  opt_design 
  write_checkpoint -force FLXG_opt.dcp
  create_report "impl_1_opt_report_drc_0" "report_drc -file FLXG_drc_opted.rpt -pb FLXG_drc_opted.pb -rpx FLXG_drc_opted.rpx"
  close_msg_db -file opt_design.pb
} RESULT]
if {$rc} {
  step_failed opt_design
  return -code error $RESULT
} else {
  end_step opt_design
  unset ACTIVE_STEP 
}

start_step place_design
set ACTIVE_STEP place_design
set rc [catch {
  create_msg_db place_design.pb
  if { [llength [get_debug_cores -quiet] ] > 0 }  { 
    implement_debug_core 
  } 
  place_design 
  write_checkpoint -force FLXG_placed.dcp
  create_report "impl_1_place_report_io_0" "report_io -file FLXG_io_placed.rpt"
  create_report "impl_1_place_report_utilization_0" "report_utilization -file FLXG_utilization_placed.rpt -pb FLXG_utilization_placed.pb"
  create_report "impl_1_place_report_control_sets_0" "report_control_sets -verbose -file FLXG_control_sets_placed.rpt"
  close_msg_db -file place_design.pb
} RESULT]
if {$rc} {
  step_failed place_design
  return -code error $RESULT
} else {
  end_step place_design
  unset ACTIVE_STEP 
}

start_step route_design
set ACTIVE_STEP route_design
set rc [catch {
  create_msg_db route_design.pb
  route_design 
  write_checkpoint -force FLXG_routed.dcp
  create_report "impl_1_route_report_drc_0" "report_drc -file FLXG_drc_routed.rpt -pb FLXG_drc_routed.pb -rpx FLXG_drc_routed.rpx"
  create_report "impl_1_route_report_methodology_0" "report_methodology -file FLXG_methodology_drc_routed.rpt -pb FLXG_methodology_drc_routed.pb -rpx FLXG_methodology_drc_routed.rpx"
  create_report "impl_1_route_report_power_0" "report_power -file FLXG_power_routed.rpt -pb FLXG_power_summary_routed.pb -rpx FLXG_power_routed.rpx"
  create_report "impl_1_route_report_route_status_0" "report_route_status -file FLXG_route_status.rpt -pb FLXG_route_status.pb"
  create_report "impl_1_route_report_timing_summary_0" "report_timing_summary -max_paths 10 -file FLXG_timing_summary_routed.rpt -pb FLXG_timing_summary_routed.pb -rpx FLXG_timing_summary_routed.rpx -warn_on_violation "
  create_report "impl_1_route_report_incremental_reuse_0" "report_incremental_reuse -file FLXG_incremental_reuse_routed.rpt"
  create_report "impl_1_route_report_clock_utilization_0" "report_clock_utilization -file FLXG_clock_utilization_routed.rpt"
  create_report "impl_1_route_report_bus_skew_0" "report_bus_skew -warn_on_violation -file FLXG_bus_skew_routed.rpt -pb FLXG_bus_skew_routed.pb -rpx FLXG_bus_skew_routed.rpx"
  close_msg_db -file route_design.pb
} RESULT]
if {$rc} {
  write_checkpoint -force FLXG_routed_error.dcp
  step_failed route_design
  return -code error $RESULT
} else {
  end_step route_design
  unset ACTIVE_STEP 
}

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  catch { write_mem_info -force FLXG.mmi }
  write_bitstream -force FLXG.bit 
  catch {write_debug_probes -quiet -force FLXG}
  catch {file copy -force FLXG.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

