# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_num_none/blk_mem_gen_num_none.xci
# IP: The module: 'blk_mem_gen_num_none' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_num_none/blk_mem_gen_num_none_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_num_none'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_num_none/blk_mem_gen_num_none.xci
# IP: The module: 'blk_mem_gen_num_none' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_num_none/blk_mem_gen_num_none_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_num_none'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
