# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/VivadoProject/FLXG/FLXG.cache/wt [current_project]
set_property parent.project_path D:/VivadoProject/FLXG/FLXG.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/VivadoProject/FLXG/FLXG.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/VivadoProject/FLXG/sources/wu.coe
add_files D:/VivadoProject/FLXG/sources/2.coe
add_files D:/VivadoProject/FLXG/sources/4.coe
add_files D:/VivadoProject/FLXG/sources/8.coe
add_files D:/VivadoProject/FLXG/sources/16.coe
add_files D:/VivadoProject/FLXG/sources/none.coe
add_files D:/VivadoProject/FLXG/sources/32.coe
add_files D:/VivadoProject/FLXG/sources/64.coe
add_files D:/VivadoProject/FLXG/sources/128.coe
add_files D:/VivadoProject/FLXG/sources/256.coe
add_files D:/VivadoProject/FLXG/sources/512.coe
add_files D:/VivadoProject/FLXG/sources/1024.coe
add_files D:/VivadoProject/FLXG/sources/2048.coe
add_files D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/scores.coe
add_files D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/test_scores.coe
add_files D:/VivadoProject/FLXG/sources/z2.coe
add_files D:/VivadoProject/FLXG/sources/z4.coe
add_files D:/VivadoProject/FLXG/sources/z8.coe
add_files D:/VivadoProject/FLXG/sources/z16.coe
add_files D:/VivadoProject/FLXG/sources/z32.coe
add_files D:/VivadoProject/FLXG/sources/z64.coe
add_files D:/VivadoProject/FLXG/sources/z128.coe
add_files D:/VivadoProject/FLXG/sources/z256.coe
add_files D:/VivadoProject/FLXG/sources/z1024.coe
add_files D:/VivadoProject/FLXG/sources/z2048.coe
add_files D:/VivadoProject/FLXG/sources/z512.coe
add_files D:/VivadoProject/FLXG/sources/fail.coe
add_files D:/VivadoProject/FLXG/sources/success.coe
add_files D:/VivadoProject/FLXG/sources/cwk.coe
add_files D:/VivadoProject/FLXG/sources/rst.coe
read_verilog -library xil_defaultlib {
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/Down_Move.v
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/Keyboard.v
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/Left_Move.v
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/Nixietube.v
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/Right_Move.v
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/Up_Move.v
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/VGA.v
  D:/VivadoProject/FLXG/FLXG.srcs/sources_1/new/FLXG.v
}
read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M_board.xdc]
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M.xdc]
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_num_none/blk_mem_gen_num_none.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_num_none/blk_mem_gen_num_none_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_cwk/img_cwk.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_cwk/img_cwk_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_2048/blk_mem_gen_2048.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_2048/blk_mem_gen_2048_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_256/blk_mem_gen_256.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_256/blk_mem_gen_256_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_64/blk_mem_gen_64.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_64/blk_mem_gen_64_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_rst/img_rst.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_rst/img_rst_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_32/blk_mem_gen_32.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_32/blk_mem_gen_32_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_128/blk_mem_gen_128.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_128/blk_mem_gen_128_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_512/blk_mem_gen_512.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_512/blk_mem_gen_512_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_fail/img_fail.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_fail/img_fail_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_success/img_success.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_success/img_success_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_2/blk_mem_gen_2_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_1024/blk_mem_gen_1024.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_1024/blk_mem_gen_1024_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_8/blk_mem_gen_8_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_16/blk_mem_gen_16.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_16/blk_mem_gen_16_ooc.xdc]

read_ip -quiet D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
set_property used_in_implementation false [get_files -all d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/VivadoProject/FLXG/FLXG.srcs/constrs_1/imports/VivadoProject/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files D:/VivadoProject/FLXG/FLXG.srcs/constrs_1/imports/VivadoProject/Nexys-4-DDR-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FLXG -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FLXG.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FLXG_utilization_synth.rpt -pb FLXG_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
