# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_success/img_success.xci
# IP: The module: 'img_success' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_success/img_success_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_success'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_success/img_success.xci
# IP: The module: 'img_success' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/img_success/img_success_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'img_success'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
