# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M.xci
# IP: The module: 'clk_wiz_65M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M.xci
# IP: The module: 'clk_wiz_65M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/VivadoProject/FLXG/FLXG.srcs/sources_1/ip/clk_wiz_65M/clk_wiz_65M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_65M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
